version: '3.8'

services:
  mcp-resend-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add your Resend API key here or use a .env file
      # - RESEND_API_KEY=your_api_key_here
    env_file:
      - .env
    restart: unless-stopped